# Generated by Django 3.2.6 on 2024-12-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelfs', to='home.shelf'),
        ),
    ]
