# Generated by Django 3.2.6 on 2024-12-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_book_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelfs', to='home.shelf'),
        ),
        migrations.AlterField(
            model_name='bookreservation',
            name='get_name',
            field=models.CharField(max_length=255),
        ),
    ]
