# Generated by Django 3.2.6 on 2024-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20241218_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservation',
            name='count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
